### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by eternaleclipse** [meltylabs/melty#1]
There are no build instructions.

Running `npm i`, I encountered the following errors:
```
user@rain:~/melty$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: code-oss-dev@1.93.0
npm ERR! Found: @xterm/xterm@5.6.0-beta.52
npm ERR! node_modules/@xterm/xterm
npm ERR!   @xterm/xterm@"5.6.0-beta.52" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @xterm/xterm@"^5.4.0" from @xterm/addon-clipboard@0.2.0-beta.35
npm ERR! node_modules/@xterm/addon-clipboard
npm ERR!   @xterm/addon-clipboard@"0.2.0-beta.35" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /home/user/.npm/_logs/2024-09-03T10_37_51_887Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/user/.npm/_logs/2024-09-03T10_37_51_887Z-debug-0.log
```

**Comment by lycaste** [comment]
you need  read vscode Developer guide ,this based on vscode

**Comment by RikenMor001** [comment]
The version of @xterm/xterm is compatible to 5.6.0 whereas the dependency file expects the version 5.4.0.
To do this, run npm install --legacy-peers-deps, this command will ignore the peer/extra dependencies that @xterm/xterm was bringing in and than you can install npm separately by running the command npm install --force and than run npm install @xterm/xterm@5.4.0
NOTE : - delete the version 5.6.0 than run npm install --force and provided you have run these two is only you should update it to 5.4.0 and this should pretty much sort the problem.

**Comment by jacksondc** [comment]
@eternaleclipse can you try running `melty_setup.sh` and see if there are any issues there? It will install through yarn rather than npm.
