### ISSUE TITLE
Can this be released as a vscode extension?

### ISSUE THREAD

**Issue by fpemud** [meltylabs/melty#10]
Is this intended to be a vscode extension or a completely new code editor?
In my opinion, release it as a vscode extension could make it more accessible for users to try it out and integrate into their existing workflow.
Are there specific reasons why it cann‘t be released as a vscode extension?

**Comment by sitestudio** [comment]
https://marketplace.visualstudio.com/items?itemName=meltylabs.melty

**Comment by jacksondc** [comment]
Melty started out as an extension but we transitioned to the app to be able to integrate much more deeply with the editor. We've stopped development on the extension.
