### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Vijaykv5** [meltylabs/melty#2]
Currently, the `CONTRIBUTING.md` have some unnecessary contents that are not part of this repository.
_[CONTRIBUTING.md](https://github.com/meltylabs/melty/blob/main/CONTRIBUTING.md)_ 
Also there are no instructions set up for contributors to get started with contributions.

**Comment by jackphuongvu** [comment]
Thank you for pointing this out. We'll look into that.

**Comment by jacksondc** [comment]
Thanks @Vijaykv5, let me update that. It'll probably take a bit of time before we get the code into a stable state and make it easy to contribute, but we'll work hard to get there.

@jackphuongvu please don't represent yourself as a maintainer.
