### ISSUE TITLE
401: Authentication error: invalid x-api-key

### ISSUE THREAD

**Issue by delphym** [meltylabs/melty#31]
Hi there, not sure what I'm doing wrong or if I missed/skipped something in the setup, but Melty worked 1st couple of days after the extension installation into VS Code on my macOS, but now each time, I'm trying to use it gives me the following error:
```
Melty encountered an error: 401 {"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"}}. Try again?
```
![image](https://github.com/user-attachments/assets/f01b3436-edd7-471f-ac89-5be3e94a8cc3)

I guess, I'd need to provide a new API key, but which one? And from where?
Maybe some instructions in [README.md](https://github.com/meltylabs/melty/blob/main/README.md) could help.

**Comment by abhi12299** [comment]
Melty uses Claude. You can set the API key by searching for `melty.anthropicApiKey` in the user preferences (`cmd+,` or `ctrl+,`)

**Comment by delphym** [comment]
Thank you for the instructions! It helped.
I had to sign up with Anthropic AI... I'd probably need to give up on Open AI.

Maybe, in the future it could be possible to switch the IA model/vendor.
