### ISSUE TITLE
./scripts/build-spectacular.sh errors and need endless manually install package with --legacy-peer-deps

### ISSUE THREAD

**Issue by ddgg** [meltylabs/melty#4]
npm error /home/me/projects/ml/melty/extensions/spectacular/node_modules/esbuild/install.js:130
npm error     throw new Error(`Expected ${JSON.stringify("0.16.17")} but got ${JSON.stringify(stdout)}`);
npm error           ^
npm error
npm error Error: Expected "0.16.17" but got "0.23.0"
npm error     at validateBinaryVersion (/home/me/projects/ml/melty/extensions/spectacular/node_modules/esbuild/install.js:130:11)
npm error     at /home/me/projects/ml/melty/extensions/spectacular/node_modules/esbuild/install.js:283:5
npm error
npm error Node.js v20.17.0

and Module not found: Error: Can't resolve '@radix-ui/react-slot' and I need install dependencies manually

  609  npm install --legacy-peer-deps posthog-js
  611  npm install --legacy-peer-deps anthropic-ai
  614  npm install --legacy-peer-deps anthropic-ai/sdk
  615  npm install --legacy-peer-deps @anthropic-ai/sdk
  618  npm install --legacy-peer-deps rewire
  620  npm install --legacy-peer-deps react-scripts
  622  npm install --legacy-peer-deps react
  624  npm install --legacy-peer-deps react-dom
  626  npm install --legacy-peer-deps diff2html
  628  npm install --legacy-peer-deps react-router-dom
  630  npm install --legacy-peer-deps react-syntax-highlighter
  632  npm install --legacy-peer-deps lucide-react
  634  npm install --legacy-peer-deps react-window
  636  npm install --legacy-peer-deps fuse.js
  638  npm install --legacy-peer-deps class-variance-authority
 
and I did not continue

**Comment by ddgg** [comment]
I'm still getting the same errors, is it possible you share your build environment like linux distro and version if you are using linux? I'm using arch and it might be the problem.
EDIT: found the melty_setup.sh, only extra thing is run "npm install esbuild@0.16.17" and it's working now

**Comment by jacksondc** [comment]
Thanks for troubleshooting @ddgg! I would think `esbuild` would be installed automatically because it's listed in dev dependencies. In any case, glad it worked!
