### ISSUE TITLE
Testing Build: Error: Activating extension 'meltylabs.melty' failed

### ISSUE THREAD

**Issue by HomeDev68** [meltylabs/melty#51]
Error: Activating extension 'meltylabs.melty' failed: Cannot find module '/workspaces/melty/extensions/spectacular/out/extension.js' Require stack: - /workspaces/melty/out/vs/loader.js - /workspaces/melty/out/bootstrap-amd.js - /workspaces/melty/out/bootstrap-fork.js.

Console logs:
[16073:0910/200307.076212:INFO:CONSOLE(29)] "Error: Activating extension 'meltylabs.melty' failed: Cannot find module '/workspaces/melty/extensions/spectacular/out/extension.js'
Require stack:
- /workspaces/melty/out/vs/loader.js
- /workspaces/melty/out/bootstrap-amd.js
- /workspaces/melty/out/bootstrap-fork.js.", source: vscode-file://vscode-app/workspaces/melty/out/vs/workbench/browser/parts/notifications/notificationsAlerts.js (29)

Reproduction:
run ./scripts/code.sh and wait for the window to load.

Attached screenshot:
![image](https://github.com/user-attachments/assets/57e0fdb5-7b76-44fb-bb01-9171643f1c36)

**Comment by abhi12299** [comment]
Did you build the extension first? See contributing.md for local setup.. seems like you didn't run melty:extension-dev npm script

**Comment by HomeDev68** [comment]
Ok I will try that.
