### ISSUE TITLE
Change the Default theme 

### ISSUE THREAD

**Issue by HomeDev68** [meltylabs/melty#52]
# Change the Default theme to establish the difference between melty and any other code editors out there.

## Suggestions
Light blue default theme to match the melty cube logo.

**Comment by wasifkhan00** [comment]
Could you please Specify the issue?

**Comment by cbh123** [comment]
Done — added a new melty_light.json. It's not perfect but it's a start :)

**Comment by HomeDev68** [comment]
@jacksondc ok
