### ISSUE TITLE
Early Access.

### ISSUE THREAD

**Issue by techydad05** [meltylabs/melty#61]
I've sent in a couple contacts on the form and haven't gotten a reply. I would love to try this app out for some web dev. Please!!

**Comment by kingabzpro** [comment]
Same. Its been 2 weeks now.

**Comment by HomeDev68** [comment]
@techydad05 @kingabzpro You have to wait for few weeks for stable builds to be released or you can build from source by yourself.

**Comment by kingabzpro** [comment]
Got it.

**Comment by kingabzpro** [comment]
Got it.

**Comment by HomeDev68** [comment]
So, @techydad05 could you please close the issue. To make way for other prominent issues. To build check contributing.md and also check the vscode build guide.
