### ISSUE TITLE
supprt for zed and other editors

### ISSUE THREAD

**Issue by opensas** [meltylabs/melty#7]
Are you planning to eventually support other editors? I was thinking about zed specifically

Thanks!

**Comment by alectrocute** [comment]
Considering this is just a whitelabeled fork of VS Code with extensions pre-installed/pre-configured, I don't think this would ever be possible without an entire rethinking of the project. I suppose they could fork Zed and do the same thing! 😅

**Comment by jacksondc** [comment]
For now we're going to focus on integrating more deeply with vscode. No plans at the moment to support Zed or other editors.
