### ISSUE TITLE
"Error: Activating extension 'Supermaven.supermaven' failed: Cannot find module 

### ISSUE THREAD

**Issue by ddgg** [meltylabs/melty#9]
"Error: Activating extension 'Supermaven.supermaven' failed: Cannot find module '/home/me/projects/ml/melty/extensions/supermaven/out/main.js'

in "extensions/supermaven" "npm i" succeed without errors and there's no "out" folder under supermaven

**Comment by abhi12299** [comment]
Had the same issue - copy the main.js and main.chat.js file in the supermaven directory into `supermaven/out/` dir

**Comment by kareemama** [comment]
First, check if the build process for the extension is completing successfully; there might be a script or configuration that should generate the out directory. Ensure that the extension’s package.json or other configuration files correctly specify the output directory and filenames. If there’s a build command defined (such as "build": "tsc"), try running it manually with npm run build to see if it generates the missing out folder and main.js file. Additionally, look for any errors during the build process that could be preventing the output from being created. Consulting the extension’s documentation might also provide specific setup or build instructions that need to be followed. If these steps don’t resolve the issue, consider reaching out to the extension’s maintainer or support channels for further assistance.

**Comment by jacksondc** [comment]
@kareemama, please don't post AI-generated content here unless it's particularly helpful.

I just got removed supermaven from default installs, so that should resolve this for now. If you want to install supermaven you can always download the VSIX (see https://www.cursor.com/how-to-install-extension).
